directories:
  input_dir: data/raw
  output_dir: data/processed
  cache_dir: data/cache
extractor:
  batch_size: 5000
  lookback_time: now-24h
llm:
  model_name: llama3
  base_url: http://host.docker.internal:11434/v1
logparser_llm:
  k_shots: 3
  loose_match_threshold: 0.8
  merge_similarity_threshold: 0.95
  embedding_model: "nomic-embed-text"
logbatcher:
  batch_size: 10
  sampler: "DPPSampler"
  cluster: "LengthCluster"
  embedding_model: "nomic-embed-text"
librelog:
  similarity_threshold: 0.85
  max_memory_size: 1000
  k_shots: 3
  enable_reflection: true
