"""F1-score of Template Accuracy

It measures whether both the static text and the masked dynamic variables (e.g., <*>) of a generated template perfectly match the oracle template. It extracts the unique sets of templates from both the parser and the ground truth to calculate True Positives, False Positives, and False Negatives, then applies the standard F1-score formula
"""

import pandas as pd

def calculate_fta(df_gt_aligned, df_parsed_aligned, filter_templates=None):
    """Calculates the F1-score of Template Accuracy (FTA).

    Compares the set of unique templates generated by the parser against 
    the set of unique ground-truth templates to calculate Precision, Recall, and F1.

    Args:
        df_gt_aligned (pd.DataFrame): Ground truth DataFrame.
        df_parsed_aligned (pd.DataFrame): Parsed results DataFrame.
        filter_templates (set, optional): Optional set of EventTemplates to limit evaluation to.

    Returns:
        float: The computed F1-score of Template Accuracy (0.0 to 1.0).
    """
    if df_gt_aligned.empty or df_parsed_aligned.empty:
        return 0.0

    # Step 1: Extract unique template sets
    if filter_templates is not None:
        gt_templates = set(df_gt_aligned[df_gt_aligned['EventTemplate'].isin(filter_templates)]['EventTemplate'].unique())
        # Filter parsed templates to only those that were generated for the targeted GT lines
        mask = df_gt_aligned['EventTemplate'].isin(filter_templates)
        parsed_templates = set(df_parsed_aligned[mask]['EventTemplate'].unique())
    else:
        gt_templates = set(df_gt_aligned['EventTemplate'].unique())
        parsed_templates = set(df_parsed_aligned['EventTemplate'].unique())

    # Step 2: Calculate Confusion Matrix Elements
    # True Positives: Templates present in BOTH ground truth and parsed output
    tp = len(gt_templates.intersection(parsed_templates))
    
    # False Positives: Extra/hallucinated templates generated by the LLM
    fp = len(parsed_templates) - tp
    
    # False Negatives: Ground-truth templates missed by the LLM
    fn = len(gt_templates) - tp

    # Step 3: Calculate Precision and Recall
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    # Step 4: Calculate F1-Score (FTA)
    if precision + recall == 0:
        return 0.0
        
    fta = 2 * (precision * recall) / (precision + recall)

    return fta